/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './sng-card.style.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './sng-card.component';
const styles_SngCardComponent:any[] = [i0.styles];
export const RenderType_SngCardComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SngCardComponent,data:{}});
export function View_SngCardComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['Snsina Card presents']))],(null as any),
      (null as any));
}
export function View_SngCardComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'sng-card',([] as any[]),
      (null as any),(null as any),(null as any),View_SngCardComponent_0,RenderType_SngCardComponent)),
      i1.ɵdid(114688,(null as any),0,i2.SngCardComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SngCardComponentNgFactory:i1.ComponentFactory<i2.SngCardComponent> = i1.ɵccf('sng-card',
    i2.SngCardComponent,View_SngCardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL29wdC9ucG1fcGFja2FnZXMvc25nLWNhcmRzL3NyYy9zbmctY2FyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vb3B0L25wbV9wYWNrYWdlcy9zbmctY2FyZHMvc3JjL3NuZy1jYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL29wdC9ucG1fcGFja2FnZXMvc25nLWNhcmRzL3NyYy9zbmctY2FyZC50ZW1wbGF0ZS5odG1sIiwibmc6Ly8vb3B0L25wbV9wYWNrYWdlcy9zbmctY2FyZHMvc3JjL3NuZy1jYXJkLmNvbXBvbmVudC50cy5TbmdDYXJkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiU25zaW5hIENhcmQgcHJlc2VudHMiLCI8c25nLWNhcmQ+PC9zbmctY2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
